import type { Grade, RunResult } from "./types.js";

const C = {
  reset: "\x1b[0m",
  dim: "\x1b[2m",
  bold: "\x1b[1m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
};

function gradeColor(g: Grade): string {
  if (g === "A" || g === "B") return C.green;
  if (g === "C" || g === "D") return C.yellow;
  return C.red;
}

const pct = (n: number): string => `${Math.round(n * 100)}%`;

/** Print a human-readable AI Safety Scorecard to the console. */
export function printScorecard(run: RunResult, opts: { verbose?: boolean; color?: boolean } = {}): void {
  const on = opts.color !== false;
  const c = on ? C : new Proxy({}, { get: () => "" }) as typeof C;
  const sc = run.scorecard;

  console.log(`\n${c.bold}AI Safety Scorecard${c.reset} ${c.dim}· ${sc.model}${c.reset}`);
  console.log(
    `${gradeColor(sc.grade)}${c.bold}  ${sc.grade}  ${c.reset} overall  ${c.dim}·${c.reset}  ` +
      `${sc.passed}/${sc.total} passed (${pct(sc.passRate)})\n`,
  );

  for (const cat of sc.categories) {
    const g = on ? gradeColor(cat.grade) : "";
    console.log(
      `  ${g}${cat.grade}${c.reset}  ${cat.category.padEnd(22)} ${cat.passed}/${cat.total} ${c.dim}(${pct(cat.passRate)})${c.reset}`,
    );
  }

  if (sc.criticalFailures.length) {
    console.log(`\n${c.red}${c.bold}Critical failures:${c.reset} ${sc.criticalFailures.join(", ")}`);
  }

  if (opts.verbose) {
    console.log("");
    for (const r of run.cases) {
      const mark = r.passed ? `${c.green}✓${c.reset}` : `${c.red}✗${c.reset}`;
      console.log(`  ${mark} ${c.dim}[${r.category}]${c.reset} ${r.name}`);
      for (const g of r.graderResults.filter((gr) => !gr.passed)) {
        console.log(`      ${c.red}└ ${g.grader}: ${g.reason}${c.reset}`);
      }
    }
  }
  console.log("");
}

// ── HTML report — the shareable artifact ────────────────────────────────────────────────────────

export interface HtmlReportOptions {
  /** Headline shown at the top. Default: "AI Safety Scorecard". */
  title?: string;
  /** What was audited — e.g. the product or model name. Shown under the title. */
  subject?: string;
  /** Timestamp for the report. Defaults to the current date. */
  generatedAt?: Date;
  /** A short closing line — e.g. who ran it / how to get the full audit. */
  footer?: string;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** A grade → hue, reused by the CSS classes below. */
function gradeClass(g: Grade): string {
  if (g === "A" || g === "B") return "pass";
  if (g === "C" || g === "D") return "warn";
  return "fail";
}

/**
 * Render a standalone, self-contained HTML scorecard — no external CSS/JS, safe to email or attach.
 * This is the artifact you hand a prospect: an at-a-glance letter grade, per-category breakdown, and
 * the specific failing cases (with grader reasons) that make "your AI has a real issue" concrete.
 */
export function renderHtmlReport(run: RunResult, opts: HtmlReportOptions = {}): string {
  const sc = run.scorecard;
  const title = opts.title ?? "AI Safety Scorecard";
  const when = (opts.generatedAt ?? new Date()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const failing = run.cases.filter((c) => !c.passed);

  const categoryRows = sc.categories
    .map((cat) => {
      const cls = gradeClass(cat.grade);
      return `        <tr>
          <td><span class="chip ${cls}">${cat.grade}</span></td>
          <td class="cat">${esc(cat.category)}</td>
          <td class="num">${cat.passed}/${cat.total}</td>
          <td class="num dim">${pct(cat.passRate)}</td>
        </tr>`;
    })
    .join("\n");

  const criticalBlock = sc.criticalFailures.length
    ? `      <div class="critical">
        <strong>Critical failures</strong>
        <ul>${sc.criticalFailures.map((n) => `<li>${esc(n)}</li>`).join("")}</ul>
      </div>`
    : "";

  const findingsBlock = failing.length
    ? `      <h2>Findings <span class="dim">— ${failing.length} case${failing.length === 1 ? "" : "s"} to fix</span></h2>
      <ul class="findings">
${failing
  .map((c) => {
    const reasons = c.graderResults
      .filter((g) => !g.passed)
      .map((g) => `<li><code>${esc(g.grader)}</code> — ${esc(g.reason)}</li>`)
      .join("");
    return `        <li class="finding">
          <div class="finding-head">
            <span class="chip fail">FAIL</span>
            <span class="finding-name">${esc(c.name)}</span>
            <span class="tag">${esc(c.category)}</span>${c.critical ? '<span class="tag crit">critical</span>' : ""}
          </div>
          <ul class="reasons">${reasons}</ul>
        </li>`;
  })
  .join("\n")}
      </ul>`
    : `      <p class="clean">No failing cases — every checked scenario passed.</p>`;

  const footer = opts.footer ?? "Generated by EvalKit — a deploy-gating LLM safety eval harness.";
  const overallCls = gradeClass(sc.grade);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}${opts.subject ? ` — ${esc(opts.subject)}` : ""}</title>
<style>
  :root {
    --ink: #16181d; --dim: #6b7280; --line: #e5e7eb; --bg: #f6f7f9;
    --pass: #15803d; --pass-bg: #dcfce7; --warn: #b45309; --warn-bg: #fef3c7;
    --fail: #b91c1c; --fail-bg: #fee2e2;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--ink);
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; }
  .sheet { max-width: 760px; margin: 32px auto; background: #fff; border: 1px solid var(--line);
    border-radius: 12px; padding: 40px; }
  header { border-bottom: 1px solid var(--line); padding-bottom: 24px; margin-bottom: 28px; }
  h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.01em; }
  .subject { color: var(--dim); font-size: 15px; }
  .meta { color: var(--dim); font-size: 13px; margin-top: 8px; }
  .overall { display: flex; align-items: center; gap: 20px; margin: 28px 0; }
  .bigGrade { font-size: 56px; font-weight: 800; line-height: 1; width: 96px; height: 96px;
    display: flex; align-items: center; justify-content: center; border-radius: 12px; }
  .bigGrade.pass { color: var(--pass); background: var(--pass-bg); }
  .bigGrade.warn { color: var(--warn); background: var(--warn-bg); }
  .bigGrade.fail { color: var(--fail); background: var(--fail-bg); }
  .overall .summary { font-size: 15px; }
  .overall .summary strong { font-size: 18px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 4px; }
  td { padding: 10px 8px; border-bottom: 1px solid var(--line); }
  td.cat { font-weight: 600; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .dim { color: var(--dim); }
  .chip { display: inline-flex; align-items: center; justify-content: center; min-width: 26px;
    padding: 2px 7px; border-radius: 6px; font-weight: 700; font-size: 13px; }
  .chip.pass { color: var(--pass); background: var(--pass-bg); }
  .chip.warn { color: var(--warn); background: var(--warn-bg); }
  .chip.fail { color: var(--fail); background: var(--fail-bg); }
  .critical { background: var(--fail-bg); border: 1px solid #fca5a5; border-radius: 8px;
    padding: 14px 18px; margin: 24px 0; color: var(--fail); }
  .critical ul { margin: 6px 0 0; padding-left: 20px; }
  h2 { font-size: 16px; margin: 32px 0 12px; }
  .findings { list-style: none; padding: 0; margin: 0; }
  .finding { border: 1px solid var(--line); border-radius: 8px; padding: 14px 16px; margin-bottom: 12px; }
  .finding-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
  .finding-name { font-weight: 600; }
  .tag { font-size: 12px; color: var(--dim); background: var(--bg); border: 1px solid var(--line);
    border-radius: 5px; padding: 1px 7px; }
  .tag.crit { color: var(--fail); border-color: #fca5a5; background: var(--fail-bg); }
  .reasons { margin: 10px 0 0; padding-left: 20px; color: var(--ink); }
  .reasons code { background: var(--bg); padding: 1px 5px; border-radius: 4px; font-size: 13px; }
  .clean { color: var(--pass); font-weight: 600; }
  footer { border-top: 1px solid var(--line); margin-top: 32px; padding-top: 18px;
    color: var(--dim); font-size: 13px; }
</style>
</head>
<body>
  <div class="sheet">
    <header>
      <h1>${esc(title)}</h1>
      ${opts.subject ? `<div class="subject">${esc(opts.subject)}</div>` : ""}
      <div class="meta">Model: ${esc(sc.model)} · ${esc(when)}</div>
    </header>

    <div class="overall">
      <div class="bigGrade ${overallCls}">${sc.grade}</div>
      <div class="summary">
        <strong>${sc.passed}/${sc.total} checks passed</strong> (${pct(sc.passRate)})<br>
        <span class="dim">${sc.categories.length} categor${sc.categories.length === 1 ? "y" : "ies"} evaluated${
          sc.criticalFailures.length ? ` · ${sc.criticalFailures.length} critical failure${sc.criticalFailures.length === 1 ? "" : "s"}` : ""
        }</span>
      </div>
    </div>

${criticalBlock}

    <table>
      <tbody>
${categoryRows}
      </tbody>
    </table>

${findingsBlock}

    <footer>${esc(footer)}</footer>
  </div>
</body>
</html>
`;
}
